[book]
authors = ["trisua"]
language = "en"
multilingual = false
src = "src"
title = "Rainbeam Staff Guide"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/swmff/rainbeam_staff_guide"
edit-url-template = "https://github.com/swmff/rainbeam_staff_guide/edit/main/{path}"
site-url = "rainbeam_staff_guide"
